<a href="https://colab.research.google.com/github/Jittiya/multivariate/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Function

``` python
def function_name(_Input_):
      do_somthing with _Input_ to produce _Output_
      return _Output_
```





```
# This is formatted as code
```



function มีส่วนสำคัญทั้งหมด 4 ส่วน

     1. บอก python ว่าเราจะเขียนฟังก์ชั่น ชื่ออะไร def function_name(): (ขาดไม่ได้)
     2. กำหนดตัวแปรที่จะเป็น input Input (ขาดได้)
     3. ส่วนประมวลผล do_something with Input to get Output (ขาดไม่ได้)
     4. ส่วน output return Output(ขาดได้)
เราใช้ เว้นวรรค (indent) เพื่อบอกขอบเขตของ code

# สร้างฟังก์ชั่น

In [ ]:
def print_name(name,surname,ID) :
      st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'
      return st
      print( 'outside function' )

การใช้ฟังก์ชั่น

In [ ]:
print_name('จิตติยา' , 'ศิริธรรมจักร' , '623021043-3')

'ชื่อ จิตติยา นามสกุล ศิริธรรมจักร ID 623021043-3'

In [ ]:
output_string = print_name('จิตติยา' , 'ศิริธรรมจักร' , '623021043-3')
print(output_string)

ชื่อ จิตติยา นามสกุล ศิริธรรมจักร ID 623021043-3


ฟังก์ชั่นไม่จำเป็นต้องมี output

In [ ]:
def print_name2(name,surname,ID) :
      st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'
      print(st)

In [ ]:
print_name2( 'จิตติยา' , 'ศิริธรรมจักร' , '623021043-3' )

ชื่อ จิตติยา นามสกุล ศิริธรรมจักร ID 623021043-3


In [ ]:
op2 = print_name2( 'จิตติยา' , 'ศิริธรรมจักร' , '623021043-3' )

ชื่อ จิตติยา นามสกุล ศิริธรรมจักร ID 623021043-3


In [ ]:
print(op2)

None


ฟังก์ชั่นไม่จำเป็นต้องมี input

In [ ]:
def Pi( ):
      return 3.14159265359

In [ ]:
# คำนวณพื้นที่วงกลมที่มีขนาดเส้นผ่านศูนย์กลางเท่ากับ 3
Pi( )*(1.5**2)

7.0685834705775

In [ ]:
def print_my_name( ):
      print( ' จิตติยา  ศิริธรรมจักร  623021043-3 ' )

In [ ]:
print_my_name( )

 จิตติยา  ศิริธรรมจักร  623021043-3 


## 1. input ของ function ใน python มีสองแบบ input ที่จำเป็นต้องใส่ กับ input ที่ไม่จำเป็นต้องใส่ (มีค่า default)
##2. เราต้องเรียง input ที่จำเป็นต้องใส่ขึ้นก่อน

In [ ]:
def print_2lines_default(name,surname,ID,grade= 'F' ):
      st = f' ชื่อ {name} นามสกุล {surname} isyl {ID}'
      print(st)
      st2=f'เกรดวิชา Multivariate >>> {grade}'
      print(st2)

In [ ]:
print_2lines_default('จิตติยา' , 'ศิริธรรมจักร' , '623021043-3' )

 ชื่อ จิตติยา นามสกุล ศิริธรรมจักร isyl 623021043-3
เกรดวิชา Multivariate >>> F


In [ ]:
print_2lines_default('จิตติยา' , 'ศิริธรรมจักร' , '623021043-3' , 'A' )

 ชื่อ จิตติยา นามสกุล ศิริธรรมจักร isyl 623021043-3
เกรดวิชา Multivariate >>> A


เราสามารถเรียกฟังก์ชั่นโดยใช้ชื่อตัวแปรอื่นของฟังก์ชั่นช่วยได้

In [ ]:
print_name2(name='จิตติยา', surname='ศิริธรรมจักร', ID='623021043-3')

ชื่อ จิตติยา นามสกุล ศิริธรรมจักร ID 623021043-3


HW3  ให้เขียน function คำนวณจำนวนวินาทีจาก เวลาต่อไปนี้

'14-15-31'

'13-00-01'

'05-49-44'

'00-00-16'

และ print ให้สวยงาม

# คำตอบ

In [ ]:
def function_time(time):
    st = time.split('-')
    ans = int(st[0]) * 3600 + int(st[1]) * 60 + int(st[2]) 
    print(f'คำนวณจำนวนวินาทีจาก {time} จะเท่ากับ {ans} วินาที')

In [ ]:
function_time('14-15-31')

คำนวณจำนวนวินาทีจาก 14-15-31 จะเท่ากับ 51331 วินาที


In [ ]:
function_time('13-00-01')

คำนวณจำนวนวินาทีจาก 13-00-01 จะเท่ากับ 46801 วินาที


In [ ]:
function_time('15-49-44')

คำนวณจำนวนวินาทีจาก 15-49-44 จะเท่ากับ 56984 วินาที


In [ ]:
function_time('00-00-16')

คำนวณจำนวนวินาทีจาก 00-00-16 จะเท่ากับ 16 วินาที


19 Jan 2021

# Numpy

Numpy -> package  สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)

Num + py   ->  Number-Numerical + python

ขั้นตอนการใช้ package
1.  ```import```  ```ชื่อ package``` #เรียกใช้ package
2.  ```ชื่อ package```.```ชื่อฟังก์ชัน``` #เรียกใช้ function 





In [1]:
import numpy

data structure  ->  array

สร้าง array  (numpy array)

In [4]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


สำคัญ
1.ชี้ค่าใน numpy array

In [6]:
mat_ex1[1,1] #[แถว,หลัก]

0.1

ถ้าไม่มี numpy array

In [7]:
list_ex1 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [16]:
list_ex1[1][1]  #list สามารภใส่ตัวเลขได้ค่าเดียวใน[]

0.1

In [17]:
print(list_ex1)
a = list_ex1[1]
print(a)
print(a[1])

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
[9.1, 0.1, 0.3]
0.1


Matrix  Operations

data 2 แบบ  ->  matrix (2D  array)  ,  scalar  (ตัวเลขค่าคงที่)

In [18]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2 = numpy.array([[2,3.7,5.9],[91,1.5,7.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


##  บวกกับลบ  matrix  ต้องเอาตัวเลขตำปหน่งเดียวกันมาบวกกัน


หน้าตาของ matrix ต้องเหมือนกัน

mat_ex0  = numpy.array([[1,2],[3,4]])
print(mat_ex0)

In [20]:
mat_ex0  = numpy.array([[1,2],[3,4]])
print(mat_ex0)

[[1 2]
 [3 4]]


In [19]:
mat_ex3 = mat_ex1 + mat_ex2
print(mat_ex3)
mat_ex4 = mat_ex1 - mat_ex2
print(mat_ex4)

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]
[[  3.2  -0.7  -1.4]
 [-81.9  -1.4  -7. ]]


In [21]:
mat_ex0 + mat_ex1

ValueError: ignored

การตรวจสอบขนาดของ  matrix

In [22]:
mat_ex3.shape

(2, 3)

In [23]:
mat_ex3.shape[0]

2

# คูณ matrix

In [25]:
print(mat_ex1)
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


In [26]:
mat_ex1 * mat_ex2  #แบบนี้ไม่ถูก มันเป็นการเอาตำแหน่งเดียวกันมาคูณกัน ไม่ใช่การคูณ matrix

array([[1.040e+01, 1.110e+01, 2.655e+01],
       [8.281e+02, 1.500e-01, 2.190e+00]])

## การคูณ matrix (แถวคูณหลัก)

( หลักของ Matrix ตัวข้างหน้า  ต้องเท่ากับแถวของ Matrix  ตัวข้างหลัง )

dot product (AAA,x),(x,ZZZ)  =  (AAA,ZZZ)

In [27]:
numpy.dot(mat_ex1,mat_ex2)  #

ValueError: ignored

In [28]:
print(mat_ex1)
print(mat_ex1.shape)
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


# Transpose  กลับแถวเป็นหลักกลับหลักเป็นแถว



ใช้คำสั่ง
```Matrix.T```



In [30]:
print(mat_ex2)
print(mat_ex2.shape)

[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


In [31]:
print(mat_ex2.T)
print(mat_ex2.T.shape)

[[ 2.  91. ]
 [ 3.7  1.5]
 [ 5.9  7.3]]
(3, 2)


In [29]:
numpy.dot(mat_ex1, mat_ex2.T)  #(2,3).(3,2)

array([[ 48.05, 510.55],
       [ 20.34, 830.44]])

In [33]:
numpy.dot(mat_ex1.T,mat_ex2) #(3,2).(2,3)  = (3,3)

array([[838.5 ,  32.89,  97.11],
       [ 15.1 ,  11.25,  18.43],
       [ 36.3 ,  17.1 ,  28.74]])

## HW 4  อธิบายการหา Determinant  และ Inverse matrix  (รูปและคำอธิบาย)